### ISSUE TITLE
Feature: Select Proton environment when creating a component

### ISSUE THREAD

**Issue by clareliguori** [awslabs/aws-proton-plugins-for-backstage#123]
Similar to #82 (select a Proton service template), some Backstage templates using the Proton plugin will allow developers to choose which Proton environments their new service should be deployed to.  It would be easier for the user to pick a Proton environment from a dropdown list than to type in the name of the environment.

For example, in this template snippet, the developer creating the Backstage component using the scaffolder will need to type in the names of the dev and prod Proton environments they want to use into a text box in the UI.
```
spec:
  parameters:
    - title: Select environments
      properties:
        dev_environment:
          title: Development Environment
          type: string
        prod_environment:
          title: Development Environment
          type: string
...
  steps:
    - id: template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          aws_proton_dev_environment_name: ${{ parameters.dev_environment }}
          aws_proton_prod_environment_name: ${{ parameters.prod_environment }}
```

Backstage supports the concept of [Field Extensions](https://backstage.io/docs/features/software-templates/writing-custom-field-extensions) which provide custom fields to capture information from the Backstage user when creating a Component.  This feature would add a custom Field Extension that lists the Proton environments available by querying the API so that the user can dynamically select it.

For example, the Backstage template would refer to the field extension for any environment parameters.
```
      properties:
        dev_environment:
          title: Development Environment
          type: string
          ui:field: AwsProtonEnvironmentPicker
        prod_environment:
          title: Development Environment
          type: string
          ui:field: AwsProtonEnvironmentPicker
```
