### ISSUE TITLE
Feature: Environment entity card

### ISSUE THREAD

**Issue by clareliguori** [awslabs/aws-proton-plugins-for-backstage#124]
Some users would like to view information about a Proton environment in the Backstage UI.  Components in the Backstage catalog could be annotated with a Proton environment ARN, perhaps alongside other information for the environment like monitoring annotations.  For example:
```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "prod-environment-123"
  description: "Production environment 123"
  annotations:
    aws.amazon.com/aws-proton-environment: arn:aws:proton:us-east-1:131296546870:environment/prod-123
    grafana/tag-selector: "prod-environment-123"
spec:
  type: environment
  lifecycle: production
  owner: "team-a"
```

The Proton plugin would provide a Proton environment entity card for the Backstage UI.  The entity card could display similar information as the Proton service entity card like the deployment status of the environment, template version, etc.
