### ISSUE TITLE
Passing different credentials for backend-plugin and scaffolder

### ISSUE THREAD

**Issue by Analect** [awslabs/aws-proton-plugins-for-backstage#217]
I followed in the installation instructions.
I created 2 new IAM users .. one for the backend-plugin with associated policy `aws-proton-backend-user` and one for the scaffolder `aws-proton-scaffolder-user`.

Back in `app-config.yaml`, how should one pass these credentials

```
aws:
  accounts:
    - accountId: 'aws-proton-backend-user'
      accessKeyId: ${MY_OTHER_ACCESS_KEY_ID}
      secretAccessKey: ${MY_OTHER_SECRET_ACCESS_KEY}
    - accountId: 'aws-proton-scaffolder-user'
      accessKeyId: ${YET_ANOTHER_ACCESS_KEY_ID}
      secretAccessKey: ${YET_ANOTHER_SECRET_ACCESS_KEY}
```

I'm not sure `accountId` can reference a user name such as `aws-proton-backend-user` . 

Is it better to associate both policies [here](https://github.com/awslabs/aws-proton-plugins-for-backstage/blob/main/docs/install.md#iam-permissions) with a single user?

Thanks.

**Comment by niallthomson** [comment]
Hey @Analect . Usually I'd expect multiple IAM identities to be used to enforce the principle of least privilege. In this case since the same entity (Backstage) is using both users can you expand a little on your reasoning for splitting them out?

**Comment by Analect** [comment]
@niallthomson ... I ended up keeping them together. 

However I hit another obstacle ref AWS credentials for different Backstage components. I know your colleague @clareliguori has done some work on this [here](https://github.com/backstage/backstage/pull/14125), but I was hitting problems running the tutorial in this repo.

I'm running a few different plugins for Backstage that require AWS credentials, among them techdocs, where I have a `gitops`  user on AWS, and I am supplying that users `accessKeyId` and `secretAccessKey`. Separately, for the AWS Proton plugin, I have a `analect-gitops-aws-proton-user` with the requisite policies per the tutorial. The Id and Secret for this user are being fed as separate env variables, per below.

```
techdocs:
  builder: 'external' # Alternatives - 'external'
  publisher:
    type: 'awsS3'
    awsS3:
      bucketName: ${TECHDOCS_BUCKET}
      region: ${AWS_REGION}
      credentials:
        accessKeyId: ${AWS_ACCESS_KEY_ID}
        secretAccessKey: ${AWS_SECRET_ACCESS_KEY}

aws:
  accounts:
    - accountId: ${AWS_PROTON_ACCOUNT_ID}
      accessKeyId: ${AWS_PROTON_USER_ACCESS_KEY_ID}
      secretAccessKey: ${AWS_PROTON_USER_SECRET_ACCESS_KEY}
```
However, when I run the `https://<my-backstage-instanace>/create/tasks/`, it errors with insufficient permissioning, since it appears to use the `gitops` user credentials rather than those of my `analect-gitops-aws-proton-user` user.

![image](https://user-images.githubusercontent.com/4063815/232051016-cf71b12d-f3c6-44b6-8b6c-f6f614de3302.png)

Since my intention is to use other plugins related to AWS in Backstage, I'd like to be able to ensure that these are getting passed into Backstage appropriately and want to try to avoid the situation described above. Should I be feeding credentials in a different way?
