### ISSUE TITLE
Feature: Select Proton service template when creating component

### ISSUE THREAD

**Issue by niallthomson** [awslabs/aws-proton-plugins-for-backstage#82]
Backstage supports the concept of [Field Extensions](https://backstage.io/docs/features/software-templates/writing-custom-field-extensions) which provide custom fields to capture information from the Backstage user when creating a Component. 

Currently the only ways to populate the Proton service name is specifying it in the Backstage template or capture with free-form text input. This feature would add a custom Field Extension that lists the Proton service templates available by querying the API so that the user can dynamically select it.

Usage in a Backstage template:

```yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: Test template
  title: Test template with custom extension
  description: Test template
spec:
  parameters:
    - title: Fill in some steps
      required:
        - protonServiceTemplate
      properties:
        protonServiceTemplate:
          title: Proton Service Template
          type: string
          description: The Proton Service Template to use
          ui:field: AwsProtonServiceTemplateExtension
[...]
  steps:
    - id: proton
      name: Create Proton Service
      action: aws:proton:create-service
      input:
        templateName: ${{ parameters.protonServiceTemplate }}
[...]
```
